# Configuración de la conexión a PostgreSQL 
quarkus.datasource.db-kind=postgresql 
quarkus.datasource.username=postgres
quarkus.datasource.password=kawai2001
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/root

quarkus.jackson.serialization.indent=true  

# Habilitar el uso de Hibernate ORM 
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.http.root-path=/gestorcontenido/v1.1

# Configuración con Vue
quarkus.http.port=8081
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:8080